name: TBGeneral
version: '0.2-BETA'
main: org.TBCreates.TBGeneral.TBGeneral
api-version: '1.21.3'
load: STARTUP
authors: [thebestharrison]
description: A plugin for all your general needs
depend: [LuckPerms]

commands:
  givebook:
    description: Force give the TBGeneral Info book to a player.
    usage: /givebook <player>
    permission: tbgeneral.givebook
    permission-message: You do not have permission to use this command.

  fly:
    description: Toggles flying for command sender.
    usage: /fly
    aliases: f
    permission: tbgeneral.fly

  gmc:
    description: Sets the player’s game mode to Creative.
    usage: /gmc
    permission: tbgeneral.admin
  gms:
    description: Sets the player’s game mode to Survival.
    usage: /gms
    permission: tbgeneral.admin
  gma:
    description: Sets the player’s game mode to Adventure.
    usage: /gma
    permission: tbgeneral.admin
  gmsp:
    description: Sets the player’s game mode to Spectator.
    usage: /gmsp
    permission: tbgeneral.admin
  menu:
    description: Opens the game mode selection menu.
    usage: /gmselect
    aliases: gmsel
    permission: tbgeneral.admin
  tbgeneral:
    description: Main command for TBGeneral plugin
    usage: /tbgeneral <reload>
    aliases: tbg
    permission: tbgeneral.admin
  tbgcommands:
    description: Useful commands for players
    usage: /tbg <sub-command>
    aliases: tbg
    permission: tbgeneral.admin
  heal:
    description: used to heal players
    usage: /heal <sub-command>
    permission: tbgeneral.admin
  bring:
    description: Useful commands to bring players
    usage: /bring <sub-command>
    permission: tbgeneral.admin
  goto:
    description: Useful commands to goto players
    usage: /goto <sub-command>
    permission: tbgeneral.admin
  openselectormenu:
    description: Opens the main menu.
    usage: /openselectormenu
    permission: tbgeneral.admin
  vanish:
    description: vanish.
    usage: /vanish
    permission: tbgeneral.admin
  commandspy:
    description: Toggle CommandSpy to see all player commands.
    permission: tbgeneral.admin
  messagespy:
    description: Toggles message spying for admins
    usage: /messagespy
    permission: tbgeneral.admin
    aliases: [msgspy]

  msg:
    description: Custom private message command
    usage: /msg <player> <message>
    aliases: [tell, whisper, w]
    permission: tbgeneral.msg
  reply:
    description: Reply to the last private message
    usage: /reply <message>
    aliases: [r]
    permission: tbgeneral.reply

  tpa:
    description: Request to teleport to a player
    usage: /tpa <player>
    permission: tbgeneral.tpa
  tpaccept:
    description: Accept a teleport request
    usage: /tpaccept
    permission: tbgeneral.tpaccept
  tpdeny:
    description: Deny a teleport request
    usage: /tpdeny
    permission: tbgeneral.tpdeny

permissions:
  tbgeneral.admin:
    description: Admin for tbgeneral plugin.
    default: op
  tbgeneral.tpa:
    description: send tpa requests for tbgeneral plugin.
    default: op
  tbgeneral.tpaccept:
    description: accept tpa requests for tbgeneral plugin.
    default: op
  tbgeneral.reply:
    description: reply to messages for tbgeneral plugin.
    default: op
  tbgeneral.msg:
    description: send messages for tbgeneral plugin.
    default: op
  tbgeneral.fly:
    description: lets you fly for tbgeneral plugin.
    default: op
  tbgeneral.givebook:
    description: lets give the book for tbgeneral plugin.
    default: op
  tbgeneral.vanish:
    description: Allows the use of /vanish
    default: op
  tbgeneral.vanish.see:
    description: Allows admins to see vanished players in tab
    default: op
